ec-/Quake3e

code/server/sv_client.c

This fixes an alignment issue caused by `printf` not accounting for the invisible q3 color codes.

fix alignment issue on /locations command

---

code/qcommon/common.c

As far as I can tell, all the other platforms/engines round the vector
components to the nearest int (even). `round` doesn't do this,
regardless of the rounding mode that is set. `rint` on the other hand
does do this.

Change Sys_SnapVector to `rint` the components for x64 linux/mingw.

---

.mailmap

This normalizes author information when using commands such as `git log` or `git shortlog`. [More information.](https://www.git-scm.com/docs/git-check-mailmap)
Pretty minor thing, but I guess it doesn't hurt to fix it :slightly_smiling_face:

Add a `.mailmap` file

---

code/qcommon/q_platform.h

E2K (Elbrus 2000) - this is VLIW/EPIC architecture, like Intel Itanium (IA-64) architecture.
Ref: https://en.wikipedia.org/wiki/Elbrus_2000

E2K: added initial support of MCST Elbrus 2000 CPU architecture

---

Makefile
code/client/cl_jpeg.c

Tested on Linux against libjpeg-turbo without jpeg8 support - works fine.
At first attempt, targa graphics and shaders would not load. `code/client/cl_jpeg.c` needs to include systemwide jpeg headers and pass a preprocessor check, so that libjpeg.so.6 won't throw a bunch of errors and warnings.
This scenario necessitates:
- the Makefile will not compile Quake's local copy of libjpeg if we choose to use system libjpeg (by default the Makefile prefers Quake's libjpeg so that nobody's workflow gets ruined)
- the Makefile will link quake3 client against system libjpeg when we want to use system jpeg
- the Makefile must add a declaration of USE_SYSTEM_JPEG to BASE_CFLAGS in order to trigger a preprocessor check that will let us enjoy targa and shader support in jpeg6 (default for Gentoo Linux' …

enabled using libjpeg provided by the system

---

code/qcommon/q_shared.h
code/unix/unix_main.c

These patches fix the build on Linux when using [Musl](https://www.musl-libc.org/), whilst not removing any functionality on Glibc.

Fix build on Musl

---

code/renderer2/tr_init.c

**Issue:**
Compiling current master with Cygwin on Windows fails because renderer 2 is missing two functions (Com_Error and Com_Printf). This happens with USE_RENDERER_DLOPEN = 1 (default).
**Changes:**
I copied those two functions from opengl renderer to the second render. This is an exact match of how it is done in the opengl renderer and in vulkan (tr_init.c), using #ifdef USE_RENDERER_DLOPEN.
**Result:**
All three renderers are compiling without errors on Cygwin/Windows 8.1 (64-bit).
**Note:**
This issue occurs even with USE_OPENGL2 = 0 (default) in the MAKEFILE. I don't want to change anything inside the MAKEFILE yet.
So nothing else will be affected with this PR.

Fixed compilation (OpenGL2).

---

code/renderervk/vk.h

-- Fixes RADV segfault on 6800XT, using XWayland and SDL2 x11 backend. Without this patch, the use of env var `MESA_VK_WSI_PRESENT_MODE=fifo` was needed to prevent the segfault. The increase of 4->8 is taken from [vkQuake3's Vk renderer code](https://github.com/suijingfeng/vkQuake3/blob/master/code/renderer_vulkan/vk_instance.h#L132).
Original issue ticket was #119.

Increase MAX_SWAPCHAIN_IMAGES to 8

---

CMakeLists.txt
cmake_modules/FindSDL2.cmake

Hello,
Here are 2 small changes I had to apply in order to make the project build on an M1.
Reasons for them are as follows:
* `CMAKE_SYSTEM_PROCESSOR` returned `arm64` for me, which resulted in using `vm_armv7l.c` file that broke linking as armv7 symbols were missing
* Setting `IMPORTED_LOCATION` to `${SDL2}/SDL` breaks linking as it resulted in an attempt to link a directory: 
```
make[2]: *** No rule to make target `/opt/homebrew/lib/libSDL2.dylib/SDL2', needed by `quake3e.app/Contents/MacOS/quake3e'. 
```
`IMPORTED_LOCATION` is supposed to point to a specific file, not a directory.
Regards,
Daniel

Mac M1 adjustments to CMake build system

---

code/botlib/l_memory.c

There are three ints (allocatedmemory, totalmemorysize, numblocks) that should be static since they are only used inside l_memory.c (and they are only used with #ifdef MEMORYMANEGER), so I declared them static and moved them down a few lines..
Moreover MEMORYMAN**E**GER is spelled wrong, it should be called MEMORYMAN**A**GER.
+ fixes potential compiler warnings.
+ renamed MEMORYMAN**E**GER to MEMORYMAN**A**GER.

Fixed l_memory/MEMORYMANAGER.

---

code/renderer2/tr_init.c

Quake3e version of https://github.com/ioquake/ioq3/pull/487.
This makes it possible to use 8× MSAA with the OpenGL 2.x renderer. (In Quake3e, this was already possible with OpenGL 1.x and Vulkan).

Allow 8× multisampling in traditional (non-framebuffer) MSAA

---

code/renderer/tr_init.c
code/renderer2/tr_init.c
code/renderervk/tr_init.c

Quake3e version of https://github.com/ioquake/ioq3/pull/488.
- Use the highest texture quality.
- Use 8× anisotropic filtering by default.
Any machine made in the last 10 years (and then some) should be able to handle this :)
It's possible to get even better rendering by using 16× anisotropic filtering, but this may have a noticeable cost on older integrated graphics.

Improve the default texture quality settings

---

code/server/sv_ccmds.c

Currently bots will be automatically kicked from server if a new map is loading, when the map was called via \devmap command.
If a map is called via regular \map command, the bots will not get kicked.
For (bot) development purposes it would be very comfortable if the bots will also move on to a new map even in developer mode. Especially because a few bot related cvars are only changeable if cheats are enabled (which is absurd when the bots are kicked to make use of these cvars.)
It's very frustrating if someone adds 64 bots, starts a map with a \devmap command and has to manually add 64 bots again.
+ In multiplayer games bots will no longer get kicked from server if a new map is started via \devmap command.
+ The default 'Singleplayer' behaviour remains the same (bots will be kicked …

Always keep bots, even with 'devmap'.

---

code/server/sv_ccmds.c

This is an exact merge of Ensiform's patch from here: https://github.com/ioquake/ioq3/commit/afa607c3b6ffed633797822871e4c4dcce124b58#diff-7357892ed859d7961b2dce3cdfdc28519c4a3781a9e4a7431226171ebed64298, and it makes life easier for people migrating from other idtech3 engines that are used to these commands.
+ 'bots' and 'all' clients can be kicked at once via 'kickbots' and 'kickall' command, or via 'kicknum'.
+ This piece of code is well tested in other ioquake3 based engines (Spearmint, WoP, etc.).
+ These changes fix annoying differences in handling relatively uniform engines (user experience).
+ All this cool work was made by Ensiform and was applied by Zturtleman. I am not the author of this work.
Thank you @ensiform!

Added kicknum, kickall, and kickbots commands, patch by Ensiform.

---

code/client/cl_console.c

This is extracted from here: https://github.com/ioquake/ioq3/commit/dfce71929a1094526f6482eeb6a0cca11f4bc7a1.
These changes will also make life easier for people that are used to this cvar ('con_autoclear' is also available in ETe).
Actually it would be nice to have 'con_autochat' available as well for Q3e, unfortunately I have to admit that I'm a bit unsure if it would work as expected in Q3e.
+ Setting the new cvar 'con_autoclear' to 0 will disable clearing console input text when console is closed (default 1).
+ This piece of code is well tested in other ioquake3 based engines (Spearmint, WoP, etc.).
+ These changes fix annoying differences in handling relatively uniform engines (user experience).
+ Again, this work was NOT made by me, Zturtleman merged this into ioquake3.

Add con_autoclear cvar.

---

code/client/cl_main.c

Scenario is the following:
1. Player opens quake3e and goes to server browser in main menu
2. Player connects to a server with a mod different than baseq3 and a password
3. "Invalid Password" message appears on the connecting screen
4. Player types password in console
5. Quake3e connects to the server and player enters the game
6. Server changes map after a while
What happens now is that player gets kicked due to invalid password, what should happen is that player can stay on the server after entering password once.
"password" cvar was restored to its default value (empty string) in point 4 when fs_game changed upon connection (in Com_GameRestart -> Cvar_Restart()).
The only downside to using CVAR_NORESTART is that client may leak password when he decides to change server. I don't think …

Fix client forgetting password when it is set in main menu

---

code/sdl/sdl_input.c

This changes SDL keyboard input to use scancodes for all keys moved on typical layouts, bringing its function in line with the win32 backend and adding support for non-latin keyboard layouts (AZERTY/Dvorak/etc are usable by rebinding, but Cyrillic/Greek are not).
Problems:
- Existing non-QWERTY SDL users with rebound keys will have wrong binds
- Native X11 backend still uses translated keycodes

Use scancodes for SDL input

---

code/botlib/be_aas_bsp.h
code/botlib/be_aas_bspq3.c
code/botlib/be_aas_cluster.c
code/botlib/be_aas_debug.c
code/botlib/be_aas_entity.c
code/botlib/be_aas_entity.h
code/botlib/be_aas_main.c
code/botlib/be_aas_move.c
code/botlib/be_aas_reach.c
code/botlib/be_aas_reach.h
code/botlib/be_aas_route.c
code/botlib/be_aas_sample.c
code/botlib/be_aas_sample.h
code/botlib/be_ai_char.c
code/botlib/be_ai_chat.c
code/botlib/be_ai_goal.c
code/botlib/be_ai_move.c
code/botlib/be_interface.c
code/botlib/botlib.h
code/botlib/l_crc.c
code/botlib/l_crc.h
code/botlib/l_libvar.c
code/botlib/l_libvar.h
code/botlib/l_log.c
code/botlib/l_log.h
code/botlib/l_precomp.c
code/botlib/l_precomp.h
code/botlib/l_script.c
code/botlib/l_script.h
code/botlib/l_struct.c

Please note that there is a [second, alternate version](https://github.com/ec-/Quake3e/pull/171) of this pull request.
Only the 'botlib' module is affected (atm).
Previously we declared a few functions that are static as such. Many other unused functions are also meant of being used as static functions (they only exist in one single file in the correct order), but they were also not declared as static, like the others.
Unfortunately if we declare them as static like the other ones, compliers will throw out a warning these functions are definded but not used.
This pull requests deals with such functions. We declare them as static and tell the compiler to not use them, because they aren't needed.
There are a few ways to tell the compiler to ignore code. By some special characters like // or …

Clean up unused (static) botlib functions V1.

---

Makefile
code/renderer2/qgl.h
code/renderer2/tr_bsp.c
code/renderer2/tr_dsa.c
code/renderer2/tr_image.c
code/renderer2/tr_shader.c
code/renderer2/tr_surface.c

Every time I reset I have to re-apply these, maybe upstream would like them. I'm still using renderer2.
Also added MacOS -ljpeg to save time compiling. It is not default behavior like on Linux.
EDIT: This is the old commit that created the error by leaving out these lines.
https://github.com/ec-/Quake3e/commit/ae4427ff7918dac1a75ae03a10290db524304c15

renderer2 fixes for dark models left over from changes some time ago

---

code/client/cl_console.c
code/client/cl_input.c
code/client/cl_main.c
code/client/snd_dma.c
code/client/snd_main.c
code/client/snd_mem.c
code/qcommon/cm_load.c
code/qcommon/common.c
code/qcommon/cvar.c
code/qcommon/files.c
code/qcommon/net_chan.c
code/qcommon/net_ip.c
code/renderer/tr_init.c
code/renderer2/tr_init.c
code/renderervk/tr_init.c
code/sdl/sdl_glimp.c
code/sdl/sdl_input.c
code/sdl/sdl_snd.c
code/server/sv_init.c
code/unix/linux_glimp.c
code/unix/linux_snd.c
code/win32/win_glimp.c
code/win32/win_input.c
code/win32/win_wndproc.c
docs/quake3e.htm

This pull request tries to describe as much CVARS as possible, as explained here: https://github.com/ec-/Quake3e/issues/188
As always feel free whatever you want to do with this pull request. Use it, change it, or skip it!
+ Add descriptions for most of the Q3e engine CVARS (by using the already existing Cvar_SetDescription functionality).
+ Establishing a constant cvar line order in a few places (1. Cvar, 2. RangeCheck, 3. Description).
+ Minor cosmetic fixes (constant cvar naming scheme - avoid mixing CamelCase).
+ I used CVAR descriptions I found at the internet. I don't understand all of them, and I don't know if the cvars really do what the description says. On the contrary, I'm pretty sure some CVARS had never worked before. No malfunctioning CVARS have been fixed.
+ Of course, …

CVARS: add more cvar descriptions.

---

code/client/cl_input.c
code/client/cl_main.c
code/client/snd_main.c
code/qcommon/common.c
code/qcommon/cvar.c
code/renderer/tr_init.c
code/renderer2/tr_init.c
code/renderervk/tr_init.c
code/sdl/sdl_input.c
code/sdl/sdl_snd.c
code/server/sv_init.c
code/unix/linux_glimp.c
code/unix/unix_main.c
code/win32/win_input.c
docs/quake3e.htm

This pull request is an extension to my previous pull request, addressing issue: https://github.com/ec-/Quake3e/issues/188
New CVAR descriptions:
cl_activeAction "Contents of this variable will be executed upon first frame of play. Note: It is cleared every time it is executed."
cl_lanForcePackets "Bypass \\cl_maxpackets for LAN games, send packets every frame."
sv_levelTimeReset "Whether or not to reset leveltime after new map loads."
joy_threshold "Threshold of joystick moving distance."
ttycon "Terminal tab-completion and history support."
ttycon_ansicolor, "Terminal display console color codes."
All these CVAR descriptions come from ETe, which **ensiform** pointed out to me.
**zturtleman** also helped me. He suggested more correct formulations for many explanations:
s_sdlBits "Bits …

More cvar descriptions and minor corrections.

---

code/renderer/tr_init.c
code/renderervk/tr_init.c

On some older devices the extension is called GL_SGIS_texture_edge_clamp. For example, NVIDIA and Intel HD Graphics on macOS.

renderers: Fix clamp to edge detection

---

code/client/cl_curl.c

Allows higher download throughput (from ~2 MB/s to ~60 MB/s at 120FPS)
From https://github.com/ioquake/ioq3/pull/313
This has no effect for curl versions older than 7.53.0 (for which the buffer can only be shrunk below 16k)
Fixes #206

Increase cURL maximum buffer size

---

code/client/cl_curl.c

Not positive percentage in Com_DL_CallbackProgress will suffice with int64/int64 * 100 staying as a double.
And if we need to change the speed being truncated to int32 for display sizeToString.

Fix deprecated warnings on modern CURL versions

---

cmake_modules/FindSDL2.cmake

Fixes the following warning as proposed [here](https://github.com/aminosbh/sdl2-cmake-modules/pull/6):
```
CMake Warning (dev) at /usr/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
The package name passed to `find_package_handle_standard_args` (SDL2main)
does not match the name of the calling package (SDL2).  This can lead to
problems in calling code that expects `find_package` result variables
(e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
cmake_modules/FindSDL2.cmake:318 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
CMakeLists.txt:171 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.
```

CMake: fix SDL2 caller and name mismatch

---

code/renderer/tr_init.c
code/renderer2/tr_init.c
code/renderervk/tr_init.c

This documents a not-very-well-known behavior of `r_lodbias`, that you'll surely appreciate once you start using it :slightly_smiling_face:
(This behavior also exists in vanilla Q3 and ioquake3.)

Improve descriptions for `r_lodbias` and `r_lodCurveError`

---

Makefile
code/asm/snd_mix_x86_64.s
code/client/cl_scrn.c
code/client/snd_mix.c
code/win32/msvc2017/botlib.vcxproj
code/win32/msvc2017/libjpeg.vcxproj
code/win32/msvc2017/libogg.vcxproj
code/win32/msvc2017/libvorbis.vcxproj
code/win32/msvc2017/quake3e-ded.vcxproj
code/win32/msvc2017/quake3e.vcxproj
code/win32/msvc2017/renderer.vcxproj
code/win32/msvc2017/renderer2.vcxproj
code/win32/msvc2017/renderervk.vcxproj

MSVC2017: enabled multi-core compilation (-faster builds)
Misc: slight speedup of main menu rendering

Sound: added optimized x86_64 mixing for mingw and unix builds

---

Makefile

This makes the game look for its files in the right place on macOS.

Define the MACOS_X flag for macOS builds

---

Makefile

I've noticed that build fails when USE_SYSTEM_VORBIS is used. The reason for that is that the required symbols are in the `vorbisfile` library and not in the `vorbis` which is currently linked with.

Link with vorbisfile. Fixes #248

---

code/server/server.h
code/server/sv_ccmds.c
code/server/sv_client.c
code/server/sv_init.c

Since the SV_ClientEnterWorld call for loading clients was removed in ed4af16763684a9b492c4c6737833531b43963e2, clients will hang if a map restart occurs while they are loading the map.
This is because a new serverid is generated during the map restart, but the new serverid is not sent to the client because it is part of the systeminfo configstring, and configstring updates are deferred for loading (CS_PRIMED) clients until ClientEnterWorld is called. However ClientEnterWorld is never called through the normal route in SV_ExecuteClientMessage because it has checks that abort any actions for clients with an outdated serverid. As a result the client is stuck, not set to active, not receiving valid snapshots, and not receiving the updated serverid.
This change fixes this problem by removing …

Don't change serverid during map restart

---

code/server/sv_client.c

Currently the server leaves clients set to CS_PRIMED during UDP downloads. This means that reliable commands from server to client can be generated, but not sent while the download is in progress. This can lead to a surge of commands being sent when the download finishes, or if enough commands are generated, the client being dropped with a "server command overflow" error.
This fix sets the client to CS_CONNECTED during downloads, which prevents unnecessary commands from being issued until the download completes and the new gamestate is sent.
Downloading clients were already set to CS_CONNECTED if a map change occurred during the download, but with this change it is set for all downloads.

Set client state to CS_CONNECTED during UDP downloads

---

code/qcommon/net_ip.c
code/unix/linux_qgl.c
code/unix/linux_snd.c
code/unix/unix_main.c

usleep(3) was declared obsolete in POSIX.1-2001 and removed in POSIX.1-2008 and nanosleep(2) was recommended to be used instead.

Use nanosleep(2) instead of usleep(3)

---

code/sdl/sdl_glimp.c

This makes Command+Tab work, so we can switch to other applications while Quake 3 is running.
It also makes it possible to show the game below the notch on Macbooks with a notch.

Use SDL_WINDOW_FULLSCREEN_DESKTOP on macOS

---

code/renderer/tr_init.c
code/renderer2/tr_init.c
code/renderervk/tr_init.c

This significantly reduces visible LOD transitions and allows curves in level geometry to be more detailed. See also https://github.com/ec-/Quake3e/pull/230.
Given how modern GPUs (even integrated graphics) can handle lots of polygons well, this has very little performance cost nowadays.

Increase default geometric detail on characters and patches

---

code/client/cl_input.c

This decreases latency if FPS is greater than or equal to 60 (since the previous default for `cl_maxpackets` was `60`), and allows for more consistent input handling. `com_maxfps` already defaults to 125, so it's a 1:1 match if your PC can render 125 FPS.
~~Increasing `snaps` further does not change anything on servers running `sv_fps 20` or `sv_fps 40`, but it ensures you automatically benefit from increased position update rates on servers running higher `sv_fps`. This in turn allows you to see players' positions more accurately compared to their real position on the server.~~
**Edit:** This PR no longer changes the default of `snaps`, see https://github.com/ec-/Quake3e/pull/299#issuecomment-2422973974.
I've been using this configuration for years now and it works just fine, even on an …

Increase default `cl_maxpackets` to 125

---

code/renderer/tr_backend.c
code/renderer/tr_init.c
code/renderer/tr_local.h
code/renderer2/tr_backend.c
code/renderer2/tr_init.c
code/renderer2/tr_local.h
code/renderervk/tr_backend.c
code/renderervk/tr_init.c
code/renderervk/tr_local.h

In Quake 3 Arena when the player goes in a teleporter entrance but has yet to arrive at the exit (probably due to the server and client architecture and ping) the renderer registers this as being in hyperspace and the screen is covered with a pure white shader. Having there brief pure white flashbangs is obviously bad for the more photosensitive players.
r_teleporerFlash is a new cvar which allows more photosensitive users to opt out of seeing a white flash every time they are in hyperspace between a teleporter entrance and its exit. For now there is only a fade to black option implemented alongside the fade to white original and default option.
The new feature is opt-in and preserves the original pure white teleporter flash as the default. Though I would be happy to change the cvar …

Implement r_teleporterFlash cvar

---

code/client/snd_codec.c
code/client/snd_dma.c

Some of default q3 models have missing sounds. It causes annoying warnings in console:
```
^3WARNING: Failed to load sound sound/player/crash/taunt.wav!
^3WARNING: could not find sound/player/crash/taunt.wav - using default
```
This patch makes these messages visible only in developer mode.

Print messages about missing sounds in developer mode only.

---

code/server/sv_client.c

Currently clients can trigger a respawn by calling "download" command followed by "donedl", which allows for exploits such as causing CTF flags to disappear in unpatched mods. This fixes the problem by adding a guard for CS_ACTIVE clients to "download" command similar to the one that already exists for "donedl". Since legitimately downloading clients should never be at CS_ACTIVE this should not affect normal functionality.

Server: don't allow active clients to start downloads

---

code/server/server.h
code/server/sv_client.c
code/server/sv_snapshot.c

Since 3f92ee47f5521a559a59c86b1a0b9ae8a3bba9a1 client->deltaMessage is set to `client->netchan.outgoingSequence - (PACKET_BACKUP + 1)` as a way to disable delta snapshots. Developer warnings like "Delta request from out of date packet" are not printed when client->deltaMessage matches this exact expression, but as `client->netchan.outgoingSequence` is incremented, warning messages may be printed when they shouldn't be.
This fix restores the behavior that client->deltaMessage is set to -1 to disable delta snapshots, allowing developer prints to correctly distinguish between delta being disabled intentionally versus by PACKET_BACKUP limit.

Server: Delta snapshot developer print fix

---

code/qcommon/files.c

Crash occurred if you:
1. Load a map
2. Change model with `model sarge/..`
3. Open `+scores`

fix: crash when viewing scores after changing model in-game
